# Generated by Django 5.1.3 on 2025-01-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
